{% set name = "google-cloud-dataform" %}
{% set version = "0.5.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a3af5c9e1c0c1ed1fb28a53f3841838a58715bdfefbd94ff84c60c147aae738f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - google-api-core >=1.34.1,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - google-api-core-grpc
    - google-auth >=2.14.1,<3.0.0dev,!=2.24.0,!=2.25.0
    # more restrictive version for python 3.13
    - proto-plus >=1.22.3,<2.0.0dev
    - protobuf >=3.20.2,<6.0.0dev,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5
    - grpc-google-iam-v1 >=0.12.4,<1.0.0dev

test:
  imports:
    - google
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-dataform
  summary: Google Cloud Dataform API client library
  license: Apache-2.0
  license_file:
    - LICENSE
  license_family: Apache
  dev_url: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-dataform

extra:
  recipe-maintainers:
    - xylar
