schema_version: 1

context:
  name: google-cloud-dataform
  version: "0.9.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/google_cloud_dataform-${{ version }}.tar.gz
  sha256: c7cdd79c23659815d7a5b044fbb242ef4ffc5f2bc0e626690352cd9e8de5b511

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - google-api-core >=1.34.1,<3.0.0,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - google-api-core-grpc
    - google-auth >=2.14.1,<3.0.0,!=2.24.0,!=2.25.0
    # more restrictive constraint for python >=3.14
    - grpcio >=1.75.1,<2.0.0
    # more restrictive constraint for python >=3.13
    - proto-plus >=1.25.0,<2.0.0
    - protobuf >=3.20.2,<7.0.0,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5
    - grpc-google-iam-v1 >=0.14.0,<1.0.0

tests:
  - python:
      imports:
        - google
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  summary: Google Cloud Dataform API client library
  license: Apache-2.0
  license_file:
    - LICENSE
  homepage: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-dataform
  repository: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-dataform

extra:
  recipe-maintainers:
    - xylar
